server:
  port: 8002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: Password123
  profiles:
    active: dev
# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chiu.cloud.entities
  configuration:
    map-underscore-to-camel-case: true
# ========================zipkin===================
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans #zipkin接收端口地址
  tracing:
    sampling:
      probability: 1.0 #默認0.1(0.1表示10次僅有一次被記錄下來)，值越大收集越即時。
